#!/bin/sh

MSG=$(awk '{printf("%s",$0)}' $1)

if [ ${#MSG} -lt 10 ]; then

  echo -e "当前提交为${#MSG}字符"
  echo -e "长度不能小于10, 请参考 https://www.conventionalcommits.org 提交规范"
  echo -e "\t$MSG"
  exit 1
fi

if [[ $MSG =~ ^(feat|fix|build|ci|perf|style|refactor|docs|test|chore):[[:blank:]].* || 
      $MSG =~ ^(feat|fix|build|ci|perf|style|refactor|docs|test|chore)\(.*\):[[:blank:]].* ||
      $MSG =~ ^revert\(.*\):[[:blank:]](feat|fix|build|ci|perf|style|refactor|docs|test|chore):[[:blank:]].* ||
      $MSG =~ ^revert\(.*\):[[:blank:]](feat|fix|build|ci|perf|style|refactor|docs|test|chore)\(.*\):[[:blank:]].* ||
      $MSG =~ ^Merge[[:blank:]].* ]]; then
  exit 0
else
  echo -e "本次提交失败, 请参考 https://www.conventionalcommits.org 提交规范"
  echo -e "\t$MSG"
  exit 1
fi
